# Generated by Django 2.2 on 2019-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptId', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('apptType', models.CharField(max_length=20)),
                ('duration', models.DurationField()),
                ('nodeNumber', models.SmallIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
    ]
